name: PlayStationDiscord Deploy

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  draft-release:
    name:  Github Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Filters for Master branch
        uses: actions/bin/filter@master
        with:
          args: branch master
      - name: 'Github Create Release'
        uses: frankjuniorr/github-create-release-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-win:
    name: PlayStationDiscord Windows builder
    needs: draft-release
    runs-on: windows-latest
    steps:
      - run: yarn release --win

  build-mac:
    name: PlayStationDiscord macOS builder
    needs: draft-release
    runs-on: macOS-latest
    steps:
      - run: yarn release --mac