name: PlayStationDiscord Sanity Check

on: [push, pull_request]

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies and lint
      - run: yarn install
      - run: yarn lint